name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # هر 12 ساعت
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: power0matin
          template: classic
          config_timezone: Asia/Tehran
          filename: metrics.svg

          # بلوک‌های پایه
          base: header, activity, community, repositories, metadata
          commits_authoring: power0matin

          # پلاگین‌ها (ترکیب چشمگیر + کاربردی)
          isocalendar: yes
          isocalendar_duration: half-year

          languages: yes
          languages_details: percentage, bytes-size
          languages_threshold: 2%

          habits: yes
          habits_facts: yes
          habits_charts: yes

          topics: yes
          topics_mode: mastered
          topics_limit: 12

          achievements: yes
          achievements_threshold: B
          achievements_secrets: yes

          # می‌تونی هر وقت خواستی این‌ها رو هم اضافه کنی:
          # stargazers: yes
          # repositories: 100
          # lines: yes
          # followup: yes

          # برای دسترسی‌های بیشتر (پرایوت/سازمان)، توکن شخصی بذار:
          # token: ${{ secrets.METRICS_TOKEN }}
